### ISSUE TITLE
Allow $ in identificators for SQL

### ISSUE THREAD

**Issue by jasir** [rubychan/coderay#164]
In #90  there is a feature for full PL/SQL support.
We would like to address at least small bug.
In this query

       select value/1000 from  v$sesstat se,v$statname sn where se.STATISTIC# = sn.STATISTIC# and  sn.name =  'CPU used by this session' and se.SID=ss.SID

You can se `v$abc` identificators. They are valid, but they are marked as error by coderay. Is there anything we can do with this?

**Comment by benbasson** [comment]
@korny if I add tests for this will you consider merging the PR? Where would I go about adding tests?

**Comment by korny** [comment]
I added a test case in https://github.com/rubychan/coderay-scanner-tests/blob/master/sql/dollar-signs.in.sql.
