### ISSUE TITLE
CodeRay 10 years Party!

### ISSUE THREAD

**Issue by shevegen** [rubychan/coderay#187]
At rubygems it is said:

https://rubygems.org/gems/coderay/versions

So the first version there to be seen happened at:

0.4.3.48 - October 1, 2005 (45.5 KB) 

So almost 10 years ago exactly.

My question will be (this issue can be closed):

Will there be a party?

PS: I am using CodeRay myself since a few years; I think the first time I heard about it was from the old german rubyforum.

**Comment by korny** [comment]
Nice that you noticed ;) Actually, I was planning to release something new. It's time for some kind of 2.0, or at least a plan for it.

**Comment by korny** [comment]
As for the party: I'm not good at organizing those, and I don't think CodeRay is important enough to make a big party ;) But if you just want to use it as an excuse to meet & drink with Rubyists in a nerdy location, I'm all for it! :dancers:
