### ISSUE TITLE
Why `test/{executable,lib,unit}/*` are not included in the gem file?

### ISSUE THREAD

**Issue by junaruga** [rubychan/coderay#205]
Why are only `test/functional/*` files included in the gem file?

coderay.gemspec
>  s.files         = `git ls-files -- lib/* test/functional/* Rakefile #{readme_file} MIT-LICENSE`.split("\n")
> s.test_files    = `git ls-files --       test/functional/*`.split("\n")

Why `test/{executable,lib,unit}/*` are not included?

**Comment by korny** [comment]
You're right, that doesn't make sense. I think tests should not be part of the gem distribution at all though. What's your opinion?

**Comment by junaruga** [comment]
> You're right, that doesn't make sense. I think tests should not be part of the gem distribution at all though. What's your opinion?

My opinion is same with you.
The Tests should not be part of the gem distribution
And `Rakefile` too.

**Comment by junaruga** [comment]
Hi @korny can you check my PR #207 ? Thanks.

**Comment by korny** [comment]
Thanks!
